import { getAccessToken } from './supabase.js';

const headers = () => {
  const token = getAccessToken();
  return { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) };
};

const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('file-input');
const uploadView = document.getElementById('upload-view');
const loadingState = document.getElementById('loading-state');
const resultView = document.getElementById('result-view');
const extractedText = document.getElementById('extracted-text');
const aiSummary = document.getElementById('ai-summary');

dropZone.ondragover = (e) => { e.preventDefault(); dropZone.classList.add('dragover'); };
dropZone.ondragleave = () => dropZone.classList.remove('dragover');
dropZone.ondrop = (e) => {
  e.preventDefault();
  dropZone.classList.remove('dragover');
  if (e.dataTransfer.files.length) handleFile(e.dataTransfer.files[0]);
};

fileInput.onchange = (e) => {
  if (e.target.files.length) handleFile(e.target.files[0]);
};

const handleFile = async (file) => {
  uploadView.style.display = 'none';
  loadingState.style.display = 'block';
  document.getElementById('loading-text').textContent = 'Reading file content...';
  
  try {
    let textContent = '';
    
    // Simple text extraction simulation for the hackathon
    // In production, you'd send the file to a backend endpoint with Tesseract or vision model
    if (file.type.startsWith('text/')) {
      textContent = await file.text();
    } else {
      // Simulate OCR for images
      await new Promise(r => setTimeout(r, 1500));
      textContent = `Simulated OCR text extracted from ${file.name}.\nThis document discusses fundamental concepts of computer science including algorithms, data structures, and the importance of Big-O notation in evaluating performance.`;
    }
    
    extractedText.textContent = textContent;
    document.getElementById('loading-text').textContent = 'Generating AI insights...';
    
    const res = await fetch('/api/ai/chat', {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({
        task: 'explain',
        prompt: `Summarize this text in bullet points and extract the key concepts for a student to learn:\n\n${textContent.substring(0, 3000)}`
      })
    });
    
    if (!res.ok) throw new Error('AI processing failed');
    const data = await res.json();
    
    // Format markdown roughly
    aiSummary.innerHTML = data.text.replace(/\n/g, '<br>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    document.getElementById('ai-provider').textContent = `Generated by ${data.provider}`;
    
    loadingState.style.display = 'none';
    resultView.style.display = 'block';
    
    document.getElementById('btn-quiz').onclick = () => {
      window.location.href = `/quiz.html?topic=${encodeURIComponent(file.name + ' concepts')}`;
    };
    
    document.getElementById('btn-flashcards').onclick = () => {
      alert('Flashcards generation will be available soon!');
    };
    
  } catch(e) {
    console.error(e);
    alert('Failed to process file');
    location.reload();
  }
};
