create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', role text not null default 'STUDENT' check (role in ('STUDENT','TEACHER','ADMIN')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', '')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table if not exists public.subjects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, color text not null default '#f47e6d', created_at timestamptz not null default now());
create table if not exists public.topics (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, name text not null, mastery numeric not null default 0 check (mastery between 0 and 100), created_at timestamptz not null default now());
create table if not exists public.study_progress (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, topic_id uuid references public.topics(id) on delete set null, minutes integer not null default 0 check (minutes >= 0), mastery numeric not null default 0, studied_on date not null default current_date, created_at timestamptz not null default now());
create table if not exists public.ai_conversations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null default 'New conversation', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.ai_messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.ai_conversations(id) on delete cascade, role text not null check (role in ('user','assistant','system')), content text not null, provider text, model text, created_at timestamptz not null default now());
create table if not exists public.ai_memory (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, memory_type text not null, content text not null, confidence numeric default 1 check (confidence between 0 and 1), created_at timestamptz not null default now());
create table if not exists public.ai_usage (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, provider text not null, model text not null, task_type text not null, tokens integer not null default 0, estimated_cost numeric(12,6) not null default 0, created_at timestamptz not null default now());
create index if not exists study_progress_user_date_idx on public.study_progress(user_id, studied_on desc);
create index if not exists ai_usage_user_date_idx on public.ai_usage(user_id, created_at desc);

alter table public.profiles enable row level security; alter table public.subjects enable row level security; alter table public.study_progress enable row level security; alter table public.ai_conversations enable row level security; alter table public.ai_messages enable row level security; alter table public.ai_memory enable row level security; alter table public.ai_usage enable row level security;
create policy "own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "own subjects" on public.subjects for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own progress" on public.study_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own conversations" on public.ai_conversations for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "conversation messages" on public.ai_messages for all using (exists (select 1 from public.ai_conversations c where c.id = conversation_id and c.user_id = auth.uid()));
create policy "own memory" on public.ai_memory for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own usage" on public.ai_usage for select using (auth.uid() = user_id);

create table if not exists public.assignments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, due_at timestamptz, status text not null default 'todo' check (status in ('todo','active','done')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.calendar_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, starts_at timestamptz not null, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.quiz_questions (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, topic_id uuid references public.topics(id) on delete set null, question_type text not null, prompt text not null, options jsonb not null default '[]', answer text, created_at timestamptz not null default now());
create table if not exists public.quiz_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, score numeric not null default 0, accuracy numeric not null default 0, duration_seconds integer default 0, created_at timestamptz not null default now());
create table if not exists public.study_groups (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.group_members (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.study_groups(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, unique(group_id, user_id), created_at timestamptz not null default now());
create table if not exists public.public_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, content text not null, visibility text not null default 'private' check (visibility in ('private','public')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.achievements (id uuid primary key default gen_random_uuid(), name text not null unique, description text not null, xp integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.user_achievements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, achievement_id uuid not null references public.achievements(id) on delete cascade, unique(user_id, achievement_id), created_at timestamptz not null default now());
create table if not exists public.study_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, started_at timestamptz not null default now(), ended_at timestamptz, minutes integer default 0, xp integer default 0, created_at timestamptz not null default now());
create table if not exists public.ai_provider_logs (id uuid primary key default gen_random_uuid(), provider text not null, model text not null, task_type text not null, status text not null, response_time_ms integer, fallback_used boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.uploaded_documents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, storage_path text not null, filename text not null, mime_type text not null, status text not null default 'uploaded', progress integer not null default 0 check (progress between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.document_chunks (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.uploaded_documents(id) on delete cascade, chunk_index integer not null, content text not null, unique(document_id, chunk_index), created_at timestamptz not null default now());
create table if not exists public.flashcards (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, topic_id uuid references public.topics(id) on delete set null, front text not null, back text not null, next_review date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.saved_prompts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, prompt text not null, created_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.daily_challenges (id uuid primary key default gen_random_uuid(), challenge_date date not null unique, title text not null, xp integer not null default 25, created_at timestamptz not null default now());
create table if not exists public.leaderboard (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, period date not null, xp integer not null default 0, unique(user_id, period), created_at timestamptz not null default now());
create table if not exists public.timetable (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, weekday integer not null check (weekday between 0 and 6), starts_at time not null, ends_at time, label text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.voice_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, transcript text, response text, duration_seconds integer default 0, created_at timestamptz not null default now());

create index if not exists assignments_user_due_idx on public.assignments(user_id, due_at);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists documents_user_status_idx on public.uploaded_documents(user_id, status);

insert into storage.buckets (id, name, public) values
 ('avatars','avatars',false), ('documents','documents',false), ('assignments','assignments',false), ('notes','notes',false), ('course-materials','course-materials',false), ('profile-images','profile-images',false)
on conflict (id) do nothing;

alter table public.assignments enable row level security; alter table public.calendar_events enable row level security; alter table public.quiz_questions enable row level security; alter table public.quiz_attempts enable row level security; alter table public.study_groups enable row level security; alter table public.group_members enable row level security; alter table public.public_notes enable row level security; alter table public.user_achievements enable row level security; alter table public.study_sessions enable row level security; alter table public.ai_provider_logs enable row level security; alter table public.uploaded_documents enable row level security; alter table public.document_chunks enable row level security; alter table public.flashcards enable row level security; alter table public.saved_prompts enable row level security; alter table public.notifications enable row level security; alter table public.leaderboard enable row level security; alter table public.timetable enable row level security; alter table public.voice_sessions enable row level security; alter table public.daily_challenges enable row level security;
create policy "own assignments" on public.assignments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own calendar" on public.calendar_events for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own questions" on public.quiz_questions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own attempts" on public.quiz_attempts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own groups" on public.study_groups for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
create policy "own memberships" on public.group_members for select using (auth.uid() = user_id);
create policy "public or own notes" on public.public_notes for select using (visibility = 'public' or auth.uid() = user_id);
create policy "own sessions" on public.study_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own documents" on public.uploaded_documents for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own chunks" on public.document_chunks for all using (exists (select 1 from public.uploaded_documents d where d.id = document_id and d.user_id = auth.uid()));
create policy "own flashcards" on public.flashcards for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own prompts" on public.saved_prompts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own notifications" on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own timetable" on public.timetable for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own voice sessions" on public.voice_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "public leaderboard" on public.leaderboard for select using (true);
create policy "own leaderboard" on public.leaderboard for insert with check (auth.uid() = user_id);
create policy "public challenges" on public.daily_challenges for select using (true);
create policy "storage own files" on storage.objects for all using (auth.uid()::text = (storage.foldername(name))[1]) with check (auth.uid()::text = (storage.foldername(name))[1]);
